config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'about', to: 'static_pages#about'

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end

  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update, :destroy]
    resources :sections, only: [:update, :destroy, :edit] do
      resources :lessons, only: [:create, :edit]
    end
    resources :courses, only: [:new, :create, :show, :update, :destroy, :edit] do
      resources :sections, only: [:create, :edit]
    end
  end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  private


end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @course.update_attributes(course_params)
    redirect_to instructor_course_path(current_course)
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to dashboard_path
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
    before_action :authenticate_user!
    before_action :require_authorized_for_current_section, only: [:create]
    before_action :require_authorized_for_current_lesson, only: [:update, :edit]

    def create
      @lesson = current_section.lessons.create(lesson_params)
      redirect_to instructor_course_path(current_section.course)
    end

    def destroy
      current_lesson.destory
      redirect_to lesson_path(current_lesson)
    end

    def edit
      @lesson = Lesson.find(params[:id])
    end

    def update
      current_lesson.update_attributes(lesson_params)
      redirect_to lesson_path(current_lesson)
    end

    private

    def require_authorized_for_current_lesson
      if current_lesson.section.course.user != current_user
        render text: 'Unauthorized', status: :unauthorized
      end
    end

    def current_lesson
      @current_lesson ||= Lesson.find(params[:id])
    end

    def require_authorized_for_current_section
      if current_section.course.user != current_user
        return render text: 'Unauthorized', status: :unauthorized
      end
    end

    helper_method :current_section
    def current_section
      @current_section ||= Section.find(params[:section_id]) rescue nil
    end

    def lesson_params
      params.require(:lesson).permit(:title, :subtitle, :video, :embed, :row_order_position)
    end

end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def edit
    @section = current_section
  end

  def update
    current_section.update_attributes(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def destroy
    current_section.destroy
    redirect_to instructor_course_path(current_course)
  end

  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    if params[:course_id]
      @current_course ||= Course.find(params[:course_id])
    else
      current_section.course
    end
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/_form.html.erb
<%= simple_form_for course, html: { multipart: true }, url: instructor_courses_path do |f| %>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :cost %>
<br/>
<p> Image Upload: </p>
<%= f.file_field :image %>
<br />
<%= f.submit "Create", class: 'enjoy-css pull-right' %>
<br />
<% end %>

app/views/instructor/courses/edit.html.erb
<br/>
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <%= simple_form_for @course, url: instructor_course_path(@course) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br/>
    <%= f.submit "Update", class: 'btn btn-default btn-sm' %>

  <!-- begin additions for delete functionality to lessons -->
    <div class="pull-right">
      <%= link_to 'Delete Course', instructor_course_path(@course), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger btn-sm' %>
    </div>
  <!-- end additions for deleting functionality to lessons -->
  <% end %>
  <br/>
</div>

app/views/instructor/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructor Courses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructor_courses.each do |instructor_course| %>
      <tr>
        <td><%= link_to 'Show', instructor_course %></td>
        <td><%= link_to 'Edit', edit_instructor_course_path(instructor_course) %></td>
        <td><%= link_to 'Destroy', instructor_course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor Course', new_instructor_course_path %>

app/views/instructor/courses/new.html.erb
<br/>
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new course</h1>

  <%= render 'form', course: @course %>

  <br/>
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.new-lesson-button').click(function(event) {
      var lessonUrl = $(event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });
  });
</script>

<script>
  $(function(){
    $('.lessons').sortable({
      update: function( event, ui) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>

<script>
  $(function(){
    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>

<br/><br/>
<div class="booyah-box col-xs-10 col-xs-offset-1">

  <!-- Edit Course -->
  <%= link_to 'Edit Course', edit_instructor_course_path(current_course), class: 'button-pill pull-right', style:'padding-left:0' %>

  <br/><br/>

  <!-- Course Preview -->
  <%= link_to 'Preview As Student', course_path(current_course), class: 'button-pill pull-right'%>


  <h1><%= current_course.title %></h1>
  <br/>

  <b><em>Course Description:</em></b>
  <br/><br/>

  <%= current_course.description %>

  <br/><br/>

<!-- Course Image Display -->
<%= image_tag current_course.image, class:'img-responsive' %>

<br/>

<!-- New Section -->
<button class="button-pill pull-right" data-toggle="modal" data-target="#newSectionModal" style="font-size:15px">
  New Section
</button>

<br/><br/>

<!-- Sections -->
<ul class="sections">

  <!-- Display Section -->
  <% current_course.sections.rank(:row_order).each do |section| %>
    <li data-update-url="<%= instructor_section_path(section) %>" class="section-li">

    <div class="header pull-left">
      <span class="glyphicon glyphicon-option-vertical"></span>
      <b><%= section.title %></b>
    </div>

    <!-- Edit Section -->
    <div class="header pull-right">
      <%= link_to 'Edit Section', edit_instructor_course_section_path(section), class: 'button-pill' %>
    <!-- New Lesson -->
      <button class="pull-right button-pill new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">New Lesson</button>
    </div>

  <br class="clr"/>
  <br class="clr"/>

<!-- Lessons -->

<ul class="lessons">
    <% section.lessons.rank(:row_order).each do |lesson| %>
      <li data-update-url="<%= instructor_lesson_path(lesson) %>">

            <div class="col-xs-1">
              <br/>
              <span class="glyphicon glyphicon-option-vertical"></span>
            </div>

              <div class="col-xs-10 text-center">
                <%= link_to lesson_path(lesson) do %>
                  <p><b><%= lesson.title %></b></p>
                  <p><%= lesson.subtitle %></p>
                <% end %>
              </div>

            <br class="clear"/>

        </li>
      <% end %>

    <br class="clear"/>

</ul>

<br class="clear"/>

</li>
<% end %>

</ul>

</div>
  <!-- Section Modal -->
  <div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="newSectionModal">Add a new section</h4>
        </div>
        <%= simple_form_for @section, url: instructor_course_sections_path(current_course), :method=>:post do |f| %>
          <div class="modal-body">
            <%= f.input :title %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>


<!-- Lesson Modal -->


<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="newLessonModal">Add a new lesson</h4>
      </div>
      <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm' } do |f| %>
        <div class="modal-body">
            <%= f.input :title %>
            <%= f.input :subtitle %>
            <%= f.input :video %><br/>
            <%= f.input :embed, label: 'Copy YouTube Link to Embed Video: ' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Submit", class: 'btn btn-primary' %>
          <% end %>
        </div>
    </div>
  </div>
</div>