config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'about', to: 'static_pages#about'

  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end

  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update, :destroy]
    resources :sections, only: [:update, :destroy, :edit] do
      resources :lessons, only: [:create, :edit]
    end
    resources :courses, only: [:new, :create, :show, :update, :destroy, :edit] do
      resources :sections, only: [:create, :edit]
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

#for models/TK class Car << ApplicationRecord 

app/models/course.rb
class Course < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :sections
  has_many :enrollments

  validates :title, presence: true
  validates :description, presence: true
  validates :cost, presence: true, numericality: {greater_than_or_equal_to: 0}

  def free?
    cost.zero?
  end

  def premium?
    ! free?
  end 

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :section
  mount_uploader :video, VideoUploader

  include RankedModel
  ranks :row_order, with_same: :section_id

  def code
    self.embed.split("v=")[1]
  end

  def next_lesson
    lesson = section.lessons.where("row_order > ?", self.row_order).rank(:row_order).first
    if lesson.blank? && section.next_section
      return section.next_section.lessons.rank(:row_order).first
    end
    return lesson
  end


end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :course
  has_many :lessons

  include RankedModel
  ranks :row_order, with_same: :course_id

  def next_section
    section = course.sections.where("row_order > ?", self.row_order).rank(:row_order).first
    return section
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :courses
  has_many :enrollments
  has_many :enrolled_courses, through: :enrollments, source: :course
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def enrolled_in?(course)
    return enrolled_courses.include?(course)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  private


end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    if current_course.premium?
    # Amount in cents
    @amount = (current_course.cost * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Open Source Content',
      :currency    => 'usd'
    )
  end

    current_user.enrollments.create(course: current_course)
    redirect_to course_path(current_course)
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  private

  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: :show

  def show
  end

  private

  helper_method :current_lesson
  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_section
    current_course = current_lesson.section.course
    if current_user.enrolled_in?(current_course) != true
      if current_lesson.section.course.user != current_user
        redirect_to course_path(current_course), alert: 'Unauthorized'
      end
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @course = Course.all
  end

  def privacy
  end

  def team
  end

  def careers
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Open Source</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
      .dropdown-menu {
        background-color: grey !important;
        color: black !important;
      }
  </style>

  <link href="http://vjs.zencdn.net/5.11.7/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/5.11.7/video.js"></script>
  <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
  <script src="https://checkout.stripe.com/checkout.js"></script>

  <link href="https://fonts.googleapis.com/css?family=Warnes" rel="stylesheet">


  </head>

<body>

<div class="total-container">

<div class="header">
  <!-- Fixed navbar -->
  <div class="navbar navbar-fixed-top" role="navigation">
    <div class="nav-container">
      <a class="navbar-brand" href="/">open source</a>

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse pull-right">
        <ul class="nav navbar-nav">
          <li class="icon-bar"><%= link_to 'Courses', courses_path %></li>
        </ul>
              <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources <b class="caret"></b></a>
                      <ul class="dropdown-menu" data-no-collapse="true">
                        <li><%= link_to 'Course List', courses_path %></li>
                        <li><%= link_to 'Teach a Course', new_instructor_course_path %></li>
                        <li><a href="#">Enroll</a></li>
                        <li class="divider"></li>
                        <li
                         class="dropdown-header"></li>
                        <% if user_signed_in? %>
                          <li><%= link_to 'My Dashboard', dashboard_path%></li>
                          <li><%= link_to 'Sign Out', destroy_user_session_path %></li>
                            <% else %>
                          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
                          <li><%= link_to 'Sign In', new_user_session_path %></li>
                        <%end %>
                      </ul>
                  </li>
              </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

</div>

<div class="body">

    <% if notice.present? %>
    <p class="alert alert-info" role="alert"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
    <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>

</div>

    <%= yield %>

    <br class="clr"/>

<div id="footer">
  <div class="container">
    <div class="col-xs-12 col-sm-3">
      <b style=text-decoration:underline >Teachers</b>
      <br /><br/>
      <%= link_to 'Teach a Course', new_instructor_course_path %>
      <br />
      <%= link_to 'My Dashboard', dashboard_path %>
    </div>
    <div class="col-xs-12 col-sm-3">
      <b style=text-decoration:underline >About</b>
      <br /><br/>
      <%= link_to 'Team', '#' %>
      <br />
      <%= link_to 'Careers', '#' %>
      <br />
      <%= link_to 'Privacy Policy', privacy_path %>
    </div>
    <div class="col-xs-12 col-sm-3">
      <b style=text-decoration:underline >Contact</b>
      <br /><br/>
      kfrench09@gmail.com
      <br />
      Brooklyn, NY
    </div>
    <div class="col-xs-12 col-sm-3 social">
      <b style=text-decoration:underline >Social</b>
      <br/>
      <br/>
      <%= link_to 'http://github.com/frenchamnesty' do %>
        <%= image_tag 'github.png', class: 'social-button' %>
      <% end %>
      <%= link_to 'https://www.linkedin.com/in/frenchkathleen' do %>
        <%= image_tag 'linkedin.png', class: 'social-button' %>
      <% end %>
        <%= image_tag 'twitter.png', class: 'social-button' %>
    </div>
  </div>
</div>


  </div>

  </body>
</html>